/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JsNavbar {
        "open": boolean;
    }
    interface JsStockFinder {
    }
    interface JsStockPrice {
        "stockSymbol": string;
    }
    interface SideDrawer {
        "myTitle": string;
        "open": boolean;
    }
}
declare global {
    interface HTMLJsNavbarElement extends Components.JsNavbar, HTMLStencilElement {
    }
    var HTMLJsNavbarElement: {
        prototype: HTMLJsNavbarElement;
        new (): HTMLJsNavbarElement;
    };
    interface HTMLJsStockFinderElement extends Components.JsStockFinder, HTMLStencilElement {
    }
    var HTMLJsStockFinderElement: {
        prototype: HTMLJsStockFinderElement;
        new (): HTMLJsStockFinderElement;
    };
    interface HTMLJsStockPriceElement extends Components.JsStockPrice, HTMLStencilElement {
    }
    var HTMLJsStockPriceElement: {
        prototype: HTMLJsStockPriceElement;
        new (): HTMLJsStockPriceElement;
    };
    interface HTMLSideDrawerElement extends Components.SideDrawer, HTMLStencilElement {
    }
    var HTMLSideDrawerElement: {
        prototype: HTMLSideDrawerElement;
        new (): HTMLSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "js-navbar": HTMLJsNavbarElement;
        "js-stock-finder": HTMLJsStockFinderElement;
        "js-stock-price": HTMLJsStockPriceElement;
        "side-drawer": HTMLSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface JsNavbar {
        "open"?: boolean;
    }
    interface JsStockFinder {
        "onJsSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface JsStockPrice {
        "stockSymbol"?: string;
    }
    interface SideDrawer {
        "myTitle"?: string;
        "open"?: boolean;
    }
    interface IntrinsicElements {
        "js-navbar": JsNavbar;
        "js-stock-finder": JsStockFinder;
        "js-stock-price": JsStockPrice;
        "side-drawer": SideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "js-navbar": LocalJSX.JsNavbar & JSXBase.HTMLAttributes<HTMLJsNavbarElement>;
            "js-stock-finder": LocalJSX.JsStockFinder & JSXBase.HTMLAttributes<HTMLJsStockFinderElement>;
            "js-stock-price": LocalJSX.JsStockPrice & JSXBase.HTMLAttributes<HTMLJsStockPriceElement>;
            "side-drawer": LocalJSX.SideDrawer & JSXBase.HTMLAttributes<HTMLSideDrawerElement>;
        }
    }
}
